### ISSUE TITLE
License - CC0

### ISSUE THREAD

**Issue by stefnotch** [jaxry/surface-plotter#2]
I tried out the website and really liked it. And, the performance was pretty nice as well, so, I ported the code to C#. More specifically, I ported [Polygonizer.js](https://github.com/jaxry/surface-plotter/blob/master/src/Polygonizer.js). However, this is a hobby project and I'd love to be able to release it under the CC0 (or MIT) license. 

May I release the ported [Polygonizer.js](https://github.com/jaxry/surface-plotter/blob/master/src/Polygonizer.js) code under a different license? 

Here is a screenshot of it:
![image](https://user-images.githubusercontent.com/10220080/45255905-c795a080-b38e-11e8-9f9c-79b3a09886ac.png)

**Comment by stefnotch** [comment]
In the future, I might port a few more files. (Such as the one that's responsible for the pretty transitions between 2 functions)

**Comment by jaxry** [comment]
Hey @stefnotch, cool project you're working on! 

I'd like to keep using the AGPL licence for this project, but I don't think that'll get in your way with whatever license you'd like to use. The Polygonizer code is an almost direct port of [Paul Bourke's page](http://paulbourke.net/geometry/polygonise/), which I believe is public domain, so have at it! 

The surface transition code (or any other individual file) isn't doing anything that original either so feel free to take inspiration from what you'd like. The AGPL license is just in place so that if anyone forks this repo and adds extra code to it, then that code would stay open source as well.

**Comment by stefnotch** [comment]
Oh, that's great! 😄 I did try to find the source, however, I had no luck. So, thank you!

And, I perfectly do understand the motivation behind using the AGPL license. 😉
